name: Build .net io module for Linux

on:
  workflow_call:
    inputs:
      repository:  # id of input
        description: 'The repository of the io module'
        required: true
        type: string
        default: ${{ github.repository }}
      dotnet-version:  # id of input
        description: 'The dotnet version that should be used for the build process.'
        required: true
        type: string
        default: 6.0.x
      project:
        description: 'The project that should be build'
        required: true
        type: string
        default: ''
      modulefile:
        description: 'How to name the output file (ZIP archive) for the module'
        required: true
        type: string
        default: 'module.zip'
      module-source-path:
        description: 'Enter the source path for the module from which the ZIP file is to be created.'
        required: false
        type: string
        default: './module-definition'
      module-info-json:
        description: 'Enter where to find the info.json for the module.'
        required: false
        type: string
        default: './module-definition/info.json'
      ui-build-path:
        description: 'Enter where to find the ui (HTML) build.'
        required: false
        type: string
        default: './src/configuration/build'
      dockerfile:
        description: 'The name of the docker file that should be added to the download'
        required: false
        type: string
        default: './.github/docker/dockerfile'
      create-single-file:
        description: 'Indicates if the dotnet module should be created as a single file'
        required: false
        type: boolean
        default: false
      rid: 
        description: 'Angabe des RID's für Windows (win-x64, win-x86, win-arm, win-arm64) oder Linux (linux-x64, linux-musl-x64, linux-arm, linux-arm64) oder MacOS (osx-x64)'
        required: false
        type: string
        default: 'linux-x64'

    secrets:
      token:
        required: true
      action-user:
        required: true
      action-token:
        required: true
      awdev-nuget-source:
        required: true
      npm-package-token:
        required: true
      npmrc-config:
        required: true

    outputs:
      download:
        description: Return the name of the artifact download
        value: 'BuildOutput'

jobs:
  build:
    name: build for ${{ inputs.rid }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repository }}
          token: ${{ secrets.token }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.dotnet-version }}

      - name: Ensure GitHub NuGet Source
        run: |
          dotnet nuget add source -u ${{ secrets.action-user }} -p ${{ secrets.action-token }} --store-password-in-clear-text --name github ${{ secrets.awdev-nuget-source }}

      - name: Create npmrc
        run: |
          echo "${{ secrets.npmrc-config }}" > .npmrc

      - name: Restore dependencies
        run: dotnet restore ${{ inputs.project }}

      - name: Build
        run: dotnet build ${{ inputs.project }} --configuration Release --force

      - name: Publish
        if: ${{ inputs.create-single-file }} == true
        run: |
          dotnet publish ${{ inputs.project }} -c Release -r ${{ inputs.rid }} -p:PublishSingleFile=true -p:IncludeNativeLibrariesInSingleFile=true -p:IncludeAllContentForSelfExtract=true -p:EnableCompressionInSingleFile=true --self-contained true -o out --force
        env:
          npm_config_userconfig: '${{ github.workspace }}/.npmrc'
          npm_config_globalconfig: '${{ github.workspace }}/.npmrc'
          NODE_AUTH_TOKEN: ${{ secrets.npm-package-token }}

      - name: Publish
        if: ${{ inputs.create-single-file }} == false 
        run: |
          dotnet publish ${{ inputs.project }} -c Release -r ${{ inputs.rid }} -o out --force
        env:
          npm_config_userconfig: '${{ github.workspace }}/.npmrc'
          npm_config_globalconfig: '${{ github.workspace }}/.npmrc'
          NODE_AUTH_TOKEN: ${{ secrets.npm-package-token }}

      - name: 'Create module definition file'
        uses: vimtor/action-zip@v1
        with:
          dest: ${{ inputs.modulefile }}
          files: ${{ inputs.module-source-path }}
          recursive: true

      - name: Get module version
        id: module-version
        uses: actiwaredevelopment/action-io-get-module-version@v0.1
        with:
          module-definition-file: './module-definition/info.json'

      - name: 'Create version information'
        uses: finnp/create-file-action@master
        env:
          FILE_NAME: './version.txt'
          FILE_DATA: '${{ steps.module-version.outputs.version }}-developer'

      - name: Add follow items to artifact
        run: |
          echo "${{ github.workspace }}/${{ inputs.modulefile }}"
          echo "${{ inputs.module-info-json }}"
          echo "${{ inputs.dockerfile }}"
          echo "${{ inputs.ui-build-path }}"
          echo "./version.txt"
          echo "./out"

      - name: 'Upload the Publish Artifact'
        uses: actions/upload-artifact@v2.2.2
        with:
          name: BuildOutput
          path: |
            ${{ github.workspace }}/${{ inputs.modulefile }}
            ${{ inputs.module-info-json }}
            ${{ inputs.dockerfile }}
            ${{ inputs.ui-build-path }}
            ./version.txt
            ./out
          retention-days: 1

