name: Build .net io module for Windows

on:
  workflow_call:
    inputs:
      artifact:  # id of input
        description: 'The name of the artifact'
        required: true
        type: string
        default: ''
      image-name:
        description: 'The name of the docker image'
        required: true
        type: string
        default: ''
      image-tag:
        description: 'The name of the tag for the docker image'
        required: true
        type: string
        default: ''
      dockerfile:
        description: 'The dockerfile that should be used'
        required: false
        type: string
        default: './.github/docker/dockerfile'

    secrets:
      docker-username:
        required: true
      docker-password:
        required: true

jobs:
  docker:
    name: publish to docker hub
    runs-on: ubuntu-latest

    steps:
      - name: 'Download Artifact'
        uses: actions/download-artifact@v2
        with: 
          name: ${{ inputs.artifact }}

      - name: Display structure of downloaded files
        run: ls -R

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}
          
      - name: 'Build and Publish to Docker Hub'
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
          file: ${{ inputs.docker-file }}
          push: true
