name: Publish to docker hub

on:
    workflow_call:
        inputs:
            # use-tar:
            #     description: 'Indication if there is a TAR file in the artifact'
            #     required: false
            #     type: boolean
            #     default: false
            artifact: # id of input
                description: 'The name of the artifact'
                required: true
                type: string
                default: ''
            image-name:
                description: 'The name of the docker image'
                required: true
                type: string
                default: ''
            image-tag:
                description: 'The name of the tag for the docker image'
                required: true
                type: string
                default: ''
            remove-tags:
                description: 'The name of the tag that should be removed'
                required: false
                type: string
            force-remove:
                description: 'The name of the tag that should be removed'
                required: false
                type: boolean
                default: false

        secrets:
            docker-username:
                required: true
            docker-password:
                required: true

jobs:
    docker:
        name: publish to docker hub
        runs-on: ubuntu-latest

        steps:
            - name: 'Download Artifact'
              uses: actions/download-artifact@v2
              with:
                  name: ${{ inputs.artifact }}

            # - name: Unpack Artifact
            #   if: ${{ inputs.use-tar }}
            #   run: tar -xf ${{ inputs.artifact }}.tar

            - name: Display structure of downloaded files
              run: ls -1Rp

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.docker-username }}
                  password: ${{ secrets.docker-password }}

            - name: 'Build and Publish to Docker Hub'
              uses: actiwaredevelopment/build-push-action@v2.11.0
              with:
                  context: .
                  tags: ${{ inputs.image-name }}:${{ inputs.image-tag }}
                  remove-tags: ${{ inputs.remove-tags }}
                  force-remove: ${{ inputs.force-remove }}
                  file: dockerfile
                  push: true
